root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/."
  bin = "./tmp/main"
  full_bin = ""
  args_bin = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_dir = ["cmd", "internal"]
  exclude_dir = ["tmp", "vendor", "frontend", "node_modules", ".git", "tests"]
  exclude_file = ["*_test.go", "test_*.go"]
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = true
  delay = 1000
  stop_on_error = true
  kill_delay = "1s"
  send_interrupt = false
  rerun = false
  rerun_delay = 500

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = ""

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true